exports.xAxisSpacing = 104;
exports.fontLineHeight = 16;
exports.strokeStyle = "rgba(0,0,0,1)";
exports.white = "#fff";
exports.blackFillStyle = "#000";
exports.canvasHeightSpareForDetails = 150;
exports.canvasWidthSpareForDetails = 100;
exports.font = "18px Arial";

exports.barChart = "bar-chart";
exports.columnChart = "column-chart";
exports.linechart = "line-chart";
exports.stepLinechart = "step-line-chart";
exports.smoothLinechart = "smooth-line-chart";
exports.columnAndLinechart = "column-and-line-chart";
exports.columnAndSmoothLinechart = "column-and-smooth-line-chart";
exports.columnAndStepLinechart = "column-and-step-line-chart";
exports.pieChart = "pie-chart";
exports.meterChart = "meter-chart";